/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTemplatesRouteImport } from './routes/api/templates'
import { Route as ApiVmsRouteImport } from './routes/api/vms'
import { Route as ApiVmsNameRouteImport } from './routes/api/vms.$name'
import { Route as ApiVmsNameLogsRouteImport } from './routes/api/vms.$name.logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRoute = ApiTemplatesRouteImport.update({
  id: '/api/templates',
  path: '/api/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVmsRoute = ApiVmsRouteImport.update({
  id: '/api/vms',
  path: '/api/vms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVmsNameRoute = ApiVmsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ApiVmsRoute,
} as any)
const ApiVmsNameLogsRoute = ApiVmsNameLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ApiVmsNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/api/vms': typeof ApiVmsRouteWithChildren
  '/api/vms/$name': typeof ApiVmsNameRouteWithChildren
  '/api/vms/$name/logs': typeof ApiVmsNameLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/api/vms': typeof ApiVmsRouteWithChildren
  '/api/vms/$name': typeof ApiVmsNameRouteWithChildren
  '/api/vms/$name/logs': typeof ApiVmsNameLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/api/vms': typeof ApiVmsRouteWithChildren
  '/api/vms/$name': typeof ApiVmsNameRouteWithChildren
  '/api/vms/$name/logs': typeof ApiVmsNameLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/templates'
    | '/api/vms'
    | '/api/vms/$name'
    | '/api/vms/$name/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/templates'
    | '/api/vms'
    | '/api/vms/$name'
    | '/api/vms/$name/logs'
  id:
    | '__root__'
    | '/'
    | '/api/templates'
    | '/api/vms'
    | '/api/vms/$name'
    | '/api/vms/$name/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTemplatesRoute: typeof ApiTemplatesRoute
  ApiVmsRoute: typeof ApiVmsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates': {
      id: '/api/templates'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vms': {
      id: '/api/vms'
      path: '/api/vms'
      fullPath: '/api/vms'
      preLoaderRoute: typeof ApiVmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vms/$name': {
      id: '/api/vms/$name'
      path: '/$name'
      fullPath: '/api/vms/$name'
      preLoaderRoute: typeof ApiVmsNameRouteImport
      parentRoute: typeof ApiVmsRoute
    }
    '/api/vms/$name/logs': {
      id: '/api/vms/$name/logs'
      path: '/logs'
      fullPath: '/api/vms/$name/logs'
      preLoaderRoute: typeof ApiVmsNameLogsRouteImport
      parentRoute: typeof ApiVmsNameRoute
    }
  }
}

interface ApiVmsNameRouteChildren {
  ApiVmsNameLogsRoute: typeof ApiVmsNameLogsRoute
}

const ApiVmsNameRouteChildren: ApiVmsNameRouteChildren = {
  ApiVmsNameLogsRoute: ApiVmsNameLogsRoute,
}

const ApiVmsNameRouteWithChildren = ApiVmsNameRoute._addFileChildren(
  ApiVmsNameRouteChildren,
)

interface ApiVmsRouteChildren {
  ApiVmsNameRoute: typeof ApiVmsNameRouteWithChildren
}

const ApiVmsRouteChildren: ApiVmsRouteChildren = {
  ApiVmsNameRoute: ApiVmsNameRouteWithChildren,
}

const ApiVmsRouteWithChildren =
  ApiVmsRoute._addFileChildren(ApiVmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTemplatesRoute: ApiTemplatesRoute,
  ApiVmsRoute: ApiVmsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
